// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ptCUIXg5e1LWJbJVghcrrFjenBQfkFM',
    appId: '1:912060212369:web:6c6df4026ba5c4d6068b30',
    messagingSenderId: '912060212369',
    projectId: 'dokan-37bbb',
    authDomain: 'dokan-37bbb.firebaseapp.com',
    databaseURL: 'https://dokan-37bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dokan-37bbb.appspot.com',
    measurementId: 'G-Z5JMPL9671',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehkxz0Z3l20BuTuJPnq58H5uGGlkvnt8',
    appId: '1:912060212369:android:27e1f92aca330fa5068b30',
    messagingSenderId: '912060212369',
    projectId: 'dokan-37bbb',
    databaseURL: 'https://dokan-37bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dokan-37bbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIBHWJhBMT667HwsRoJZTy8EhHZ3Crqqg',
    appId: '1:912060212369:ios:81f2917effd4f40c068b30',
    messagingSenderId: '912060212369',
    projectId: 'dokan-37bbb',
    databaseURL: 'https://dokan-37bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dokan-37bbb.appspot.com',
    androidClientId: '912060212369-94pvccvamsa1rt6idap270bn6iutv1fl.apps.googleusercontent.com',
    iosClientId: '912060212369-qgkn8aphb8v5pfmbb558aeno5aepiigj.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigationTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIBHWJhBMT667HwsRoJZTy8EhHZ3Crqqg',
    appId: '1:912060212369:ios:81f2917effd4f40c068b30',
    messagingSenderId: '912060212369',
    projectId: 'dokan-37bbb',
    databaseURL: 'https://dokan-37bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dokan-37bbb.appspot.com',
    androidClientId: '912060212369-94pvccvamsa1rt6idap270bn6iutv1fl.apps.googleusercontent.com',
    iosClientId: '912060212369-qgkn8aphb8v5pfmbb558aeno5aepiigj.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigationTesting',
  );
}
